# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: generate test coverage
      run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2.8.2

      with:
        profile: cover.out
        local-prefix: github.com/cyberimp/crackingCodeInterview
        threshold-total: 95

        ## when token is not specified (value '') this feature is turend off
        ## in this example badge is created and committed only for main brach
        git-token: ${{ github.ref_name == 'master' && secrets.GITHUB_TOKEN || '' }}
        ## name of branch where badges are stored
        ## ideally this should be orphan branch (see below how to create this branch)
        git-branch: badges